Repository conda/conda-build, pull requests merged in 2019-10, with the labels that each got.

#3752 Add a warning when a received a file on RECIPE_PATH
  conda_build/utils.py
  news/fb-3746-recipe-path-warning.rst
  tests/test_utils.py
Labels: cla-signed

#3741 Add `extra` to `outputs` in `FIELDS`
  conda_build/metadata.py
  tests/test-recipes/split-packages/_extra_metadata/meta.yaml
Labels: cla-signed

#3759 Test with `setup.py` in a subdirectory
  tests/test-recipes/metadata/source_setup_py_data_subdir/bld.bat
  tests/test-recipes/metadata/source_setup_py_data_subdir/build.sh
  tests/test-recipes/metadata/source_setup_py_data_subdir/meta.yaml
  tests/test_api_build.py
Labels: cla-signed

#3753 Hide values of environment variables
  conda_build/cli/main_build.py
  conda_build/config.py
  conda_build/environ.py
  news/suppress-variables.rst
  tests/test-recipes/metadata/_script_env_warnings/bld.bat
  tests/test-recipes/metadata/_script_env_warnings/build.sh
  tests/test-recipes/metadata/_script_env_warnings/meta.yaml
  tests/test_api_build.py
Labels: cla-signed

#3744 Expunge the need for Xcode in post
  conda_build/post.py
Labels: cla-signed

#3772 Release notes for 3.18.10
  docs/source/release-notes.rst
Labels: cla-signed

#3778 DOC update docs for subpackage tests
  docs/source/resources/define-metadata.rst
  news/doc_sub_pkg.rst
Labels: documentation

#3773 fixed a missing .lower() on two tar_xf related util functions
  conda_build/utils.py
Labels: cla-signed

#3782 Optimise use of fnmatch in which_package()
  conda_build/inspect_pkg.py
Labels: cla-signed, enhancement

#3766 Do not consider .ignore files when searching with ripgrep
  conda_build/build.py
Labels: cla-signed

#3786 Fix UserWarnings regarding recipe path
  conda_build/cli/main_build.py
  conda_build/utils.py
  tests/test_cli.py
  tests/test_utils.py
Labels: cla-signed

#3785 Add windows platform on Azure
  appveyor.yml
  azure-pipelines.yml
  tests/test_api_build.py
  tests/test_api_debug.py
  tests/test_api_render.py
  tests/test_subpackages.py
Labels: cla-signed

#3788 Update badges
  README.rst
Labels: cla-signed

#3677 Make build.sh files of skeletons shellcheck clean
  azure-pipelines.yml
  conda_build/build.py
  conda_build/skeletons/cpan.py
  conda_build/skeletons/cran.py
  conda_build/skeletons/luarocks.py
  conda_build/skeletons/rpm.py
  news/skeleton_build_sh_shellcheck_clean.rst
  tests/test_api_skeleton.py
Labels: cla-signed

#3789 Changed conda build to conda-build
  docs/source/concepts/recipe.rst
  docs/source/index.rst
  docs/source/install-conda-build.rst
  docs/source/resources/activate-scripts.rst
  docs/source/resources/add-win-start-menu-items.rst
  docs/source/resources/commands/conda-build.rst
  docs/source/resources/commands/conda-convert.rst
  docs/source/resources/commands/conda-develop.rst
  docs/source/resources/commands/conda-index.rst
  docs/source/resources/commands/conda-inspect-channels.rst
  docs/source/resources/commands/conda-inspect-linkages.rst
  docs/source/resources/commands/conda-inspect-objects.rst
  docs/source/resources/commands/conda-inspect.rst
  docs/source/resources/commands/conda-metapackage.rst
  docs/source/resources/commands/conda-render.rst
  docs/source/resources/commands/conda-skeleton-cpan.rst
  docs/source/resources/commands/conda-skeleton-cran.rst
  docs/source/resources/commands/conda-skeleton-pypi.rst
  docs/source/resources/commands/conda-skeleton.rst
  docs/source/resources/define-metadata.rst
  docs/source/resources/make-relocatable.rst
  docs/source/resources/style-guide.rst
  docs/source/resources/tutorial-template.rst
  docs/source/resources/use-shared-libraries.rst
  docs/source/resources/variants.rst
  docs/source/user-guide/environment-variables.rst
  docs/source/user-guide/index.rst
Labels: cla-signed

#3790 Standardized project name to conda-build
  docs/source/conf.py
Labels: cla-signed
