Repository conda/conda-build, pull requests merged in 2022-12, with the labels that each got.

#4663 Change Zstd compression default to 19
  conda_build/cli/main_build.py
  conda_build/config.py
  news/zstd_def_19
Labels: cla-signed

#4665 Fix: Build environments not activated
  conda_build/build.py
  conda_build/environ.py
  conda_build/metadata.py
  conda_build/utils.py
  conda_build/windows.py
  news/4665-fix-activation-path
  tests/test_api_build.py
Labels: cla-signed

#4670 Fix skip workflow
  .github/workflows/tests-skip.yml
Labels: cla-signed

#4669 Release 3.23.3
  .authors.yml
  CHANGELOG.md
  news/4664-skip-testing-non-code
  news/4665-fix-activation-path
  news/zstd_def_19
Labels: cla-signed

#4674 Pin black for darker
  .pre-commit-config.yaml
Labels: cla-signed

#4621 Add Allure reporting, update Python version test matrix, and prune test_api_build.py
  .github/workflows/tests.yml
  conda_build/conda_interface.py
  conda_build/convert.py
  conda_build/variants.py
  setup.py
  tests/test-recipes/metadata/_unicode_in_tarball/meta.yaml
  tests/test-recipes/metadata/numpy_build/run_test.bat
  tests/test-recipes/metadata/numpy_build/run_test.py
  tests/test-recipes/metadata/numpy_build/run_test.sh
  tests/test-recipes/metadata/numpy_build_run/run_test.bat
  tests/test-recipes/metadata/numpy_build_run/run_test.py
  tests/test-recipes/metadata/numpy_build_run/run_test.sh
  tests/test-recipes/metadata/python_build_run/run_test.bat
  tests/test-recipes/metadata/python_build_run/run_test.py
  tests/test-recipes/metadata/python_build_run/run_test.sh
  tests/test_api_build.py
  tests/test_api_skeleton.py
  tests/test_post.py
  tests/utils.py
Labels: source::anaconda, cla-signed

#4675 Use GH Action instead of `on` path filtering
  .github/workflows/tests-skip.yml
  .github/workflows/tests.yml
Labels: cla-signed, sprint

#4679 Move tar-ing into separate step to avoid shadowing test results
  .github/workflows/tests.yml
Labels: source::anaconda, cla-signed, sprint

#4678 Update action versions to avoid Node.js 12 deprecation notices
  .github/workflows/docs.yml
  .github/workflows/tests.yml
Labels: source::anaconda, cla-signed, sprint

#4677 Remove logic branching for `conda_43`/`conda_44`/`conda_45`/`conda_46`/`conda_47`
  conda_build/build.py
  conda_build/conda_interface.py
  conda_build/render.py
  conda_build/utils.py
  news/4677-remove-pre-conda413-code
  tests/test_api_build.py
  tests/test_index.py
Labels: source::anaconda, cla-signed, sprint
