Repository conda/conda-build, pull requests merged in 2023-03, with the labels that each got.

#4790 Remove unnecessary reassignments and unused vars
  conda_build/conda_interface.py
Labels: source::anaconda, cla-signed, type::tech-debt

#4599 Add C compiler dep when `.xs` files are found.
  conda_build/skeletons/cpan.py
  news/4599-add-cpan-xs-detection
  tests/test_api_skeleton_cpan.py
Labels: cla-signed

#4776 Document build.force_use_keys and build.force_ignore_keys
  docs/source/resources/define-metadata.rst
Labels: type::documentation, cla-signed, source::community

#4797 Drop Python 3.7 support.
  .github/workflows/tests.yml
  conda_build/cli/main_render.py
  conda_build/skeletons/pypi.py
  news/4797-drop-python37-support
  setup.py
  tests/test_index.py
Labels: cla-signed

#4443 Drop dependency on Setuptools
  .pre-commit-config.yaml
  conda_build/skeletons/cpan.py
  conda_build/skeletons/pypi.py
  conda_build/variants.py
  conda_build/version.py
  recipe/meta.yaml
  setup.py
  tests/test_api_skeleton.py
Labels: cla-signed

#4803 Add tests for #4763
  conda_build/render.py
  news/4763-subdir
  tests/test_render.py
Labels: cla-signed

#4791 Some minor code cleanup
  conda_build/index.py
  conda_build/metapackage.py
  conda_build/os_utils/elf.py
Labels: cla-signed

#4801 Release 3.24.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/4580-update-broken-links
  news/4592-perl-core-module-detection
  news/4599-add-cpan-xs-detection
  news/4677-remove-pre-conda413-code
  news/4691-update-test-matrix
  news/4719-anaconda-cloud-needs-changed-to-anacondaorg-in-conda-build-docs
  news/4728-deprecate-CrossPlatformStLink
  news/4763-subdir
  news/4767-reenable-coverage-reporting
  news/4781-convert-manual-clone-fixture
  news/4797-drop-python37-support
  news/gh-4318-Fixes-git-lfs-error.rst
  news/tomllib-tomli
Labels: cla-signed

#4818 Stop using pending deprecation `get_prefix`
  conda_build/cli/main_develop.py
  conda_build/cli/main_inspect.py
  conda_build/conda_interface.py
Labels: cla-signed

#4825 skip troubled skeleton tests; grayskull is available
  tests/test_api_skeleton.py
  tests/test_api_skeleton_cran.py
Labels: cla-signed

#4831 Drop `conda < 4.3.2` check
  conda_build/build.py
Labels: cla-signed
