Repository conda/conda-build, pull requests merged in 2023-04, with the labels that each got.

#4734 Misc. documentation fixes
  conda_build/cli/main_inspect.py
  conda_build/cli/main_render.py
  docs/source/concepts/package-naming-conv.rst
  docs/source/concepts/recipe.rst
  docs/source/user-guide/getting-started.rst
  docs/source/user-guide/tutorials/building-conda-packages.rst
  docs/source/user-guide/wheel-files.rst
Labels: type::documentation, cla-signed

#4826 `create_test.py`: Add type hints and refactor to use pathlib
  conda_build/create_test.py
  docs/source/resources/define-metadata.rst
  tests/test_create_test.py
Labels: cla-signed

#4837 Deprecate `ns_cfg()` in `metadata.py`
  conda_build/jinja_context.py
  conda_build/metadata.py
  conda_build/variants.py
Labels: source::anaconda, cla-signed, type::tech-debt

#4843 Deprecate Python 2 silliness and use `os.makedirs(exists_ok=True)`
  conda_build/config.py
  conda_build/index.py
  news/4843-config-cleanup
Labels: cla-signed

#4844 Replace `makefile` with `Path.touch`
  tests/test_utils.py
Labels: cla-signed

#4817 Require the source when rendering if load_file_data is used
  conda_build/metadata.py
  news/4817-require-source-when-load-file-data-used
  tests/test-recipes/metadata/jinja_load_toml_from_source/meta.yaml
  tests/test-recipes/metadata/jinja_load_toml_from_source/src/pyproject.toml
Labels: cla-signed

#4692 Add svn source credential support
  conda_build/metadata.py
  conda_build/source.py
  docs/source/resources/define-metadata.rst
  news/4692-add-svn-source-credential-support
Labels: type::feature, cla-signed, source::community

#4849 Fix typo in `error_overdepending` field
  tests/test-recipes/metadata/_macos_tbd_handling/meta.yaml
Labels: cla-signed

#4845 Enable `xattr` test for macOS
  news/4845-enable-xattr-test-macos
  tests/conftest.py
  tests/test_api_build.py
Labels: cla-signed

#4857 Enable canary builds for release branches
  .github/workflows/tests.yml
Labels: cla-signed
