Repository conda/conda-build, pull requests merged in 2023-01, with the labels that each got.

#4683 `test_license_family.py`: combine tests into parameterized test
  tests/test_license_family.py
Labels: source::anaconda, cla-signed, sprint

#4694 Recompress .tar.bz2 test archives; skip enough tests to pass before getting cancelled.
  .github/workflows/tests.yml
  tests/archives/flask-0.11.1-py_0.tar.bz2
  tests/archives/fly-2.5.2-0.tar.bz2
  tests/archives/nano-2.4.1-0.tar.bz2
  tests/archives/spiffy-test-app-0.5-pyh6afbcc8_0.tar.bz2
  tests/archives/test_index_of_removed_pkg-1.0-1.tar.bz2
  tests/test_index.py
Labels: cla-signed

#4695 Speedup `test_subpackages.py::test_intradependencies`
  tests/test-recipes/split-packages/_intradependencies/conda_build_config.yaml
  tests/test-recipes/split-packages/_intradependencies/install-lib1.sh
  tests/test-recipes/split-packages/_intradependencies/install-lib2.sh
  tests/test-recipes/split-packages/_intradependencies/install-py1.sh
  tests/test-recipes/split-packages/_intradependencies/install-py2.sh
  tests/test-recipes/split-packages/_intradependencies/install-r1.sh
  tests/test-recipes/split-packages/_intradependencies/install-r2.sh
  tests/test-recipes/split-packages/_intradependencies/meta.yaml
Labels: cla-signed, sprint

#4648 Cleanup replay variables & use setup-miniconda
  .github/workflows/tests.yml
  ci/github/.condarc
  ci/github/activate_conda
  ci/github/install_conda_build_test_deps
  ci/github/run_conda_forge_build_setup_osx
  ci/github/setup_pytest_replay
  tests/conftest.py
  tests/requirements-linux.txt
  tests/requirements-macos.txt
  tests/requirements-windows.txt
  tests/requirements.txt
  tests/test-recipes/metadata/_c_vendoring_detection/conda_build_config.yaml
  tests/test-recipes/metadata/_macos_tbd_handling/conda_build_config.yaml
  tests/test-recipes/metadata/_macos_tbd_handling/meta.yaml
  tests/test-recipes/metadata/_overdepending_detection/conda_build_config.yaml
  tests/test-recipes/metadata/_overlinking_detection/conda_build_config.yaml
  tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/conda_build_config.yaml
  tests/test-recipes/metadata/_rpath/conda_build_config.yaml
  tests/test-recipes/metadata/_run_exports_in_outputs/conda_build_config.yaml
  tests/test_api_build.py
Labels: source::anaconda, cla-signed, sprint

#4702 Add misc. fixes to conda-build documentation
  docs/source/concepts/channels.rst
  docs/source/concepts/generating-index.rst
  docs/source/concepts/index.rst
  docs/source/concepts/package-naming-conv.rst
  docs/source/concepts/recipe.rst
  docs/source/index.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/tutorials/building-conda-packages.rst
Labels: type::documentation, source::anaconda, cla-signed

#4691 Adjust testing matrix
  .github/workflows/tests.yml
  news/4691-update-test-matrix
Labels: cla-signed, sprint

#4704 Make further changes to conda-build docs
  docs/source/concepts/channels.rst
  docs/source/concepts/generating-index.rst
  docs/source/concepts/index.rst
  docs/source/index.rst
  docs/source/user-guide/tutorials/building-conda-packages.rst
Labels: type::documentation, source::anaconda, cla-signed, sprint

#4709 Mark flaky test as serial & flaky to avoid macOS SDK race condition
  tests/test_api_build.py
Labels: source::anaconda, cla-signed

#4696 Speedup `test_variants.py::test_get_package_variants*`
  .pre-commit-config.yaml
  tests/test-recipes/variants/variant_recipe/meta.yaml
  tests/test_variants.py
  tests/utils.py
  tests/variant_recipe/build_config.yaml
Labels: cla-signed, sprint

#4721 Refactor `test_api_update_index.py` to use `pathlib.Path`
  tests/test_api_update_index.py
Labels: source::anaconda, cla-signed

#4724 Remove unused `test_api_inspect.py` tests & global variable
  tests/test_api_inspect.py
Labels: source::anaconda, cla-signed

#4726 Combine `test_render.py` duplicate tests with pytest parametrize
  tests/test_render.py
Labels: source::anaconda, cla-signed

#4727 Minimize `test_os_utils_external.py::test_find_executable` test and add Windows support
  tests/test_os_utils_external.py
Labels: source::anaconda, cla-signed

#4723 Inline `test_api_build_go_package.py` fixture
  tests/test_api_build_go_package.py
  tests/utils.py
Labels: source::anaconda, cla-signed

#4712 Label `variants_conda_build_sysroot` fixture
  tests/conftest.py
Labels: source::anaconda, cla-signed

#4713 Bump actions/cache version
  .github/workflows/tests.yml
Labels: source::anaconda, cla-signed

#4714 Inline fixtures in `tests/test_variants.py`
  tests/conftest.py
  tests/test-recipes/variants/03_ignore_version_reduces_matrix/meta.yaml
  tests/test-recipes/variants/03_numpy_matrix/conda_build_config.yaml
  tests/test-recipes/variants/03_numpy_matrix/meta.yaml
  tests/test_variants.py
Labels: source::anaconda, cla-signed

#4722 Inline `test_api_build_dll_package.py` recipe fixture
  tests/test_api_build_dll_package.py
  tests/utils.py
Labels: source::anaconda, cla-signed

#4728 Refactor `test_misc.py` and deprecate `CrossPlatformStLink`
  conda_build/_link.py
  conda_build/build.py
  conda_build/conda_interface.py
  news/4728-deprecate-CrossPlatformStLink
  tests/test_misc.py
Labels: source::anaconda, cla-signed

#4731 Refactor `test_pypi_skeleton.py` to use parametrize and convert `OrderedDict` to `dict`
  tests/test_pypi_skeleton.py
Labels: source::anaconda, cla-signed

#4719 Replaced instances of Anaconda Cloud with anaconda.org.
  docs/source/index.rst
  docs/source/user-guide/tutorials/building-conda-packages.rst
  news/4719-anaconda-cloud-needs-changed-to-anacondaorg-in-conda-build-docs
Labels: cla-signed

#4720 Prune/update `test_variant.py` file
  tests/test_variants.py
Labels: source::anaconda, cla-signed, type::testing

#4735 Updating `test_utils.py` file
  tests/test_utils.py
Labels: source::anaconda, cla-signed, type::testing

#4737 Updating `test_subpackages.py`
  tests/test-recipes/split-packages/_variant_override/conda_build_config.yaml
  tests/test-recipes/split-packages/python_test_dep/conda_build_config.yaml
  tests/test_subpackages.py
Labels: source::anaconda, cla-signed, type::testing

#4738 Update `test_source.py` file
  tests/test_source.py
Labels: source::anaconda, cla-signed, type::testing

#4725 Refactor `test_published_examples.py` to use test parameterization
  tests/test_published_examples.py
  tests/utils.py
Labels: source::anaconda, cla-signed

#4741 `test_create_test.py`: Convert tests into parametrized test
  tests/test_create_test.py
Labels: source::anaconda, cla-signed

#4742 Remove unused test fixtures
  tests/test_api_build_conda_v2.py
  tests/test_api_build_dll_package.py
  tests/test_api_build_go_package.py
  tests/test_api_convert.py
  tests/test_api_render.py
  tests/test_api_skeleton.py
  tests/test_api_test.py
  tests/test_build.py
  tests/test_cli.py
  tests/test_develop.py
  tests/test_inspect.py
  tests/test_metadata.py
  tests/test_post.py
  tests/test_published_examples.py
  tests/test_utils.py
  tests/test_variants.py
Labels: source::anaconda, cla-signed, type::testing

#4736 `test_api_skeleton_cran.py`: Inline parametrize, use pathlib, update CRAN packages
  tests/test_api_skeleton_cran.py
Labels: source::anaconda, cla-signed

#4747 `test_api_render.py`: remove unused `skipif` and converted `unittest.mock` to pytest-mocker
  tests/test_api_render.py
Labels: source::anaconda, cla-signed

#4746 `test_build.py`: removed unnecessary `skipif` markers and converted `os.path` to `pathlib`
  tests/test_build.py
Labels: source::anaconda, cla-signed

#4745 `test_metadata.py`: Combine native compiler metadata tests
  tests/test_metadata.py
Labels: source::anaconda, cla-signed

#4744 `test_jinja_context.py`: remove unnecessary `skipif` clause and convert `tmpdir` to `tmp_path`
  tests/test_jinja_context.py
Labels: source::anaconda, cla-signed

#4743 `test_patch.py`: Expand patch strip level test to cover more cases
  conda_build/source.py
  tests/test_patch.py
Labels: source::anaconda, cla-signed

#4729 Minor `test_cran_skeleton.py` refactor
  conda_build/skeletons/cran.py
  tests/test_cran_skeleton.py
  tests/utils.py
Labels: source::anaconda, cla-signed

#4739 `test_develop.py`: Refactor to use pathlib & abstract tests
  tests/test_develop.py
Labels: source::anaconda, cla-signed

#4748 `test_api_skeleton.py`: Reorg fixtures, remove pre-Python 2.7 condition, require `ruamel.yaml`
  tests/requirements.txt
  tests/test_api_skeleton.py
Labels: source::anaconda, cla-signed

#4749 `test_cli.py`: split into subcommand specific test files
  tests/cli/test_main_build.py
  tests/cli/test_main_convert.py
  tests/cli/test_main_debug.py
  tests/cli/test_main_develop.py
  tests/cli/test_main_index.py
  tests/cli/test_main_inspect.py
  tests/cli/test_main_metapackage.py
  tests/cli/test_main_render.py
  tests/cli/test_main_skeleton.py
  tests/test_cli.py
Labels: source::anaconda, cla-signed

#4757 `test_api_debug`: collapse all debug tests into parametrize
  tests/test_api_debug.py
Labels: source::anaconda, cla-signed
