Repository conda/conda-build, pull requests merged in 2023-07, with the labels that each got.

#4929 Issue/4633
  Makefile
  docs/source/resources/package-spec.rst
  news/4633-update-conda-package-docs
Labels: cla-signed

#4923 Install `allure-pytest` from `conda-forge`
  .github/workflows/tests.yml
  tests/requirements.txt
Labels: cla-signed

#4903 avoid duplicate logging by preventing propagation from the conda_build logger to the root logger
  conda_build/utils.py
  news/4903-duplicate-logging
Labels: cla-signed

#4936 Update `tests.yml` to match workflow in conda/conda
  .github/workflows/tests.yml
Labels: source::anaconda, cla-signed, type::task

#4183 Replace number stringification hack with custom YAML loader
  conda_build/metadata.py
  tests/test_metadata.py
Labels: source::anaconda, cla-signed

#4184 Added conjunction to comma_join, fixed islist
  conda_build/utils.py
Labels: source::anaconda, cla-signed

#4941 Merge `3.26.x` branch back into `main`
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/3998-drop-duplicate-get_summary-call
  news/4633-update-conda-package-docs
  news/4787-fix-leaf
  news/4834-drop-extra-jinja-pkg-names-from-docs
  news/4850-Fix-unintended-warnings
  news/4901-log-extra-meta-data
  news/4903-duplicate-logging
  news/4912-fix-resolved_packages-test-failure
  news/4914-fix-test_relative_git_url_submodule_clone
  news/4921-convert-entrypoints-to-plugins
Labels: cla-signed

#4947 [3.25.x] Build ePub, PDF and zipped HTML docs as well.
  .readthedocs.yml
Labels: cla-signed

#4946 [3.26.x] Build ePub, PDF and zipped HTML docs as well.
  .readthedocs.yml
Labels: cla-signed

#4945 Build ePub, PDF and zipped HTML docs as well.
  .readthedocs.yml
Labels: cla-signed

#4943 Update conda-build recipe file
  recipe/meta.yaml
Labels: cla-signed
