Repository conda/conda-build, pull requests merged in 2023-02, with the labels that each got.

#4761 Remove unnecessary fixtures
  tests/test_api_build.py
  tests/test_published_examples.py
  tests/test_subpackages.py
  tests/utils.py
Labels: source::anaconda, cla-signed

#4765 format environ.py with black
  conda_build/environ.py
  conda_build/utils.py
Labels: cla-signed

#4769 Remove More Unused Test Fixtures
  tests/test_api_build.py
  tests/test_index.py
  tests/test_metadata.py
Labels: cla-signed

#4763 Install downstream packages in correct `subdir`
  conda_build/render.py
Labels: source::anaconda, cla-signed

#4318 Fixes the git lfs error by adding git lfs fetching
  conda_build/source.py
  news/gh-4318-Fixes-git-lfs-error.rst
Labels: type::bug, source::anaconda, cla-signed

#4783 Use tomli or Python 3.11 tomllib
  conda_build/jinja_context.py
  news/tomllib-tomli
  recipe/meta.yaml
  setup.py
  tests/requirements.txt
Labels: cla-signed

#4781 Convert manual conda_build_test_recipe clone into a fixture
  .github/workflows/tests.yml
  CONTRIBUTING.md
  Makefile
  conda_build/api.py
  news/4781-convert-manual-clone-fixture
  tests/cli/test_main_build.py
  tests/conftest.py
  tests/test-recipes/fail/source_git_jinja2_oops/meta.yaml
  tests/test-recipes/metadata/_osx_is_app_missing_python_app/meta.yaml
  tests/test-recipes/metadata/_source_git_jinja2_relative_git_url/meta.yaml
  tests/test-recipes/metadata/_source_git_jinja2_relative_path/meta.yaml
  tests/test-recipes/metadata/_source_setuptools/meta.yaml
  tests/test-recipes/metadata/empty_sections/meta.yaml
  tests/test-recipes/metadata/empty_with_build_script/meta.yaml
  tests/test-recipes/metadata/jinja2_build_str/meta.yaml
  tests/test-recipes/metadata/osx_is_app/meta.yaml
  tests/test-recipes/metadata/source_multiple/meta.yaml
  tests/test-recipes/metadata/source_path/meta.yaml
  tests/test-recipes/metadata/source_regex/meta.yaml
  tests/test-recipes/metadata/source_regex_from_recipe_dir/meta.yaml
  tests/test-recipes/metadata/source_setup_py_data/meta.yaml
  tests/test-recipes/metadata/source_setup_py_data_subdir/meta.yaml
  tests/test-recipes/published_code/building_jinja2_direct_env_vars/meta.yaml
  tests/test-recipes/published_code/building_jinja2_environ/meta.yaml
  tests/test-recipes/published_code/building_jinja2_setup_py_data/meta.yaml
  tests/test-recipes/split-packages/_alternate_type_wheel/meta.yaml
  tests/test-recipes/split-packages/_git_in_output_version/meta.yaml
  tests/test_api_build.py
  tests/test_api_test.py
  tests/test_published_examples.py
  tests/test_subpackages.py
Labels: cla-signed

#4580 Updated broken example recipe links.
  docs/source/concepts/recipe.rst
  docs/source/user-guide/recipes/sample-recipes.rst
  news/4580-update-broken-links
Labels: type::documentation, cla-signed

#4662 Update conda-build.rst with missing args
  docs/source/resources/commands/conda-build.rst
Labels: cla-signed

#4767 Re-enable coverage reporting to codecov
  .github/workflows/tests.yml
  news/4767-reenable-coverage-reporting
Labels: cla-signed
