Repository conda/conda-build, pull requests merged in 2024-07, with the labels that each got.

#5371 Replace `sys.exit` calls in `conda_build/metadata.py`
  conda_build/metadata.py
  tests/test_api_build.py
  tests/test_metadata.py
Labels: cla-signed

#5393 Replace `sys.exit` calls in `conda_build/inspect_pkg.py`
  conda_build/inspect_pkg.py
  tests/cli/test_main_inspect.py
  tests/test_inspect.py
  tests/test_inspect_pkg.py
  tests/test_post.py
Labels: cla-signed, type::task

#5352 Update `conda build --test recipe/` deprecation
  conda_build/build.py
  conda_build/deprecations.py
  news/3192-deprecate-testing-recipes
  tests/test_build.py
Labels: cla-signed

#5402 `sys.exit` removals from `build.py`
  conda_build/build.py
  tests/test_build.py
Labels: cla-signed

#5404 Prefer sysroot matching subdir when there are multiple
  conda_build/post.py
  news/5404-sysroot-prefer
  tests/test-recipes/metadata/_sysroot_detection/build.sh
  tests/test-recipes/metadata/_sysroot_detection/conda_build_config.yaml
  tests/test-recipes/metadata/_sysroot_detection/main.c
  tests/test-recipes/metadata/_sysroot_detection/meta.yaml
  tests/test_api_build.py
Labels: cla-signed

#5231 Skip compressed repodata for internal index
  conda_build/index.py
  news/5205-repodata-json-only
  pyproject.toml
  recipe/meta.yaml
  tests/requirements.txt
Labels: source::anaconda, cla-signed

#5406 Remove more `24.7.x` deprecations
  conda_build/build.py
  conda_build/metadata.py
  news/5406-remove-deprecated-code
Labels: cla-signed, type::task

#5176 allow LIEF to fail when using patchelf
  conda_build/post.py
  news/5176-lief-fail
Labels: cla-signed

#5418 Changelog 24.7.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/3192-deprecate-testing-recipes
  news/4821-include-file-hash
  news/5176-lief-fail
  news/5205-repodata-json-only
  news/5216-files-exclude
  news/5281-perf-deepcopy
  news/5333-remove-24.7.x-deprecations
  news/5344-report-rendered
  news/5350-subdir-cross
  news/5355-deprecate-check_external
  news/5359-validate-run-constrained
  news/5368-pip-outputs
  news/5384-test-log-level
  news/5387-ci-osx-sdk
  news/5404-sysroot-prefer
  news/5406-remove-deprecated-code
Labels: cla-signed, type::task

#5419 Merge `24.7.x` into `main`
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/3192-deprecate-testing-recipes
  news/4821-include-file-hash
  news/5176-lief-fail
  news/5205-repodata-json-only
  news/5216-files-exclude
  news/5281-perf-deepcopy
  news/5333-remove-24.7.x-deprecations
  news/5344-report-rendered
  news/5350-subdir-cross
  news/5355-deprecate-check_external
  news/5359-validate-run-constrained
  news/5368-pip-outputs
  news/5384-test-log-level
  news/5387-ci-osx-sdk
  news/5404-sysroot-prefer
  news/5406-remove-deprecated-code
Labels: cla-signed, type::task

#5428 Clear libmamba `.solv` cache
  tests/test_api_build.py
Labels: cla-signed

#5322 ensure undefined script_env variables are undefined in multi-output build environment
  conda_build/build.py
  news/5322-undefine-build-vars
  tests/test-recipes/split-packages/_build_script_relying_on_missing_var/meta.yaml
  tests/test_subpackages.py
Labels: cla-signed

#5434 Check whether WSL is installed
  conda_build/build.py
  news/5434-check-for-WSL
  tests/test_api_build.py
Labels: cla-signed
