Repository conda/conda-build, pull requests merged in 2024-03, with the labels that each got.

#5203 Remove deprecations slated for 24.3
  .github/workflows/tests.yml
  conda_build/build.py
  conda_build/cli/main_render.py
  conda_build/conda_interface.py
  conda_build/environ.py
  conda_build/index.py
  conda_build/inspect_pkg.py
  conda_build/metadata.py
  conda_build/noarch_python.py
  conda_build/post.py
  conda_build/render.py
  conda_build/skeletons/cpan.py
  conda_build/skeletons/pypi.py
  conda_build/source.py
  conda_build/utils.py
  news/5203-remove-deprecations
  pyproject.toml
  recipe/meta.yaml
  tests/requirements.txt
  tests/test_source.py
  tests/test_variants.py
Labels: cla-signed

#5221 Port deprecated `conda.auxlib.packaging.get_version_from_git_tag` to `conda_build`
  conda_build/conda_interface.py
  conda_build/environ.py
  news/5221-deprecate-get_version_from_git_tag
Labels: cla-signed

#5219 Deprecate `Environment` in favor of `PrefixData`
  conda_build/build.py
  conda_build/environ.py
  news/5219-deprecate-Environment
  tests/test_environ.py
Labels: cla-signed

#5208 Deprecate `conda_build.api.get_output_file_path`
  conda_build/api.py
  docs/source/resources/variants.rst
  news/5208-deprecate-get_output_file_path
  tests/cli/test_main_build.py
  tests/test_api_build.py
  tests/test_api_consistency.py
  tests/test_api_render.py
  tests/test_render.py
  tests/test_subpackages.py
Labels: cla-signed

#5226 Defer `.index._apply_instructions` and `.conda_interface.get_index` deprecations
  conda_build/conda_interface.py
  conda_build/index.py
  news/5203-remove-deprecations
Labels: cla-signed

#5228 Add compatibility for LIEF=0.14
  conda_build/os_utils/liefldd.py
  news/5228-lief-0.14-compat
Labels: cla-signed

#5146 Sync CI with conda
  .github/condarc
  .github/workflows/tests.yml
  pyproject.toml
  tests/requirements-Linux.txt
  tests/requirements-Windows.txt
  tests/requirements-ci.txt
  tests/requirements-macOS.txt
  tests/requirements.txt
Labels: cla-signed

#5223 Update advice on installing conda-build
  docs/source/user-guide/getting-started.rst
Labels: cla-signed

#5236 Ensure we are testing development conda-build
  .github/workflows/tests.yml
  tests/conftest.py
Labels: cla-signed

#5233 Enable CodSpeed and add select lines benchmark
  .github/workflows/tests.yml
  news/5233-enable-codspeed
  tests/test_inspect_pkg.py
  tests/test_metadata.py
Labels: cla-signed

#5240 Release 24.3.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/4867-arm64-msvc-env-cmd-no-op
  news/5195-fix-stdlib-variant
  news/5196-deprecate-bdist-conda
  news/5199-deprecate-have_prefix_files
  news/5203-remove-deprecations
  news/5208-deprecate-get_output_file_path
  news/5219-deprecate-Environment
  news/5221-deprecate-get_version_from_git_tag
  news/5228-lief-0.14-compat
Labels: cla-signed

#5222 Deprecating `conda_build.conda_interface`
  conda_build/__init__.py
  conda_build/build.py
  conda_build/cli/main_build.py
  conda_build/cli/main_metapackage.py
  conda_build/conda_interface.py
  conda_build/config.py
  conda_build/environ.py
  conda_build/index.py
  conda_build/inspect_pkg.py
  conda_build/metadata.py
  conda_build/os_utils/external.py
  conda_build/render.py
  conda_build/skeletons/pypi.py
  conda_build/utils.py
  conda_build/variants.py
  news/5222-deprecating-conda_interface
  tests/test_api_build.py
  tests/test_api_render.py
  tests/test_subpackages.py
Labels: source::anaconda, cla-signed, type::deprecation

#5214 Clarify run_exports/weak in meta.yaml docs
  docs/source/resources/define-metadata.rst
Labels: type::documentation, cla-signed, source::community

#5217 docs: source.git_rev defaults to HEAD (meta.yaml)
  docs/source/resources/define-metadata.rst
Labels: type::documentation, cla-signed, source::community

#5247 Merge `24.3.x` back into `main`
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/4867-arm64-msvc-env-cmd-no-op
  news/5195-fix-stdlib-variant
  news/5196-deprecate-bdist-conda
  news/5199-deprecate-have_prefix_files
  news/5203-remove-deprecations
  news/5208-deprecate-get_output_file_path
  news/5219-deprecate-Environment
  news/5221-deprecate-get_version_from_git_tag
  news/5228-lief-0.14-compat
Labels: cla-signed

#5246 Add benchmark for high `pin_subpackage` count recipe
  tests/test-recipes/metadata/_pin_subpackage_benchmark/meta.yaml
  tests/test_api_render.py
Labels: cla-signed

#5249 Add selectors to pin_subpackage_benchmark recipe
  tests/test-recipes/metadata/_pin_subpackage_benchmark/meta.yaml
Labels: cla-signed

#5218 docs: source URL can be a list (meta.yaml)
  docs/source/resources/define-metadata.rst
Labels: type::documentation, cla-signed, source::community

#5202 Only fetch `lfs` files for specific `git_ref`
  conda_build/source.py
Labels: cla-signed

#5244 Treat deprecation warnings as errors
  conda_build/build.py
  conda_build/conda_interface.py
  conda_build/config.py
  conda_build/environ.py
  conda_build/os_utils/external.py
  conda_build/utils.py
  news/5222-deprecating-conda_interface
  pyproject.toml
  tests/test_environ.py
Labels: cla-signed
